development: &postgis
 adapter: postgis
 database: fallingfruit_db
 username: {{ dbuser }}
 password: {{ dbpass }}
 host: localhost
 pool: 5
 timeout: 5000
 postgis_extension: true
 script_dir: /usr/share/postgresql/9.1/contrib/postgis-2.0
production:
 <<: *postgis
test:
 <<: *postgis
 database: fallingfruit_test_db
