---

- hosts: fallingfruit
  user: root
  sudo: yes
  gather_facts: no

  vars:
    username: fallingfruit_user
    ffhome: /home/{{ username }}/fallingfruit
    dbpass: fjsf73jysststsu899990
    dbuser: fallingfruit_user

  tasks:
  - name: Install dependencies
    apt: pkg={{ item }} state=installed update-cache=yes
    with_items:
    - git-core
    - curl
    - zlib1g-dev
    - build-essential
    - libssl-dev
    - libreadline-dev
    - libyaml-dev
    - libsqlite3-dev
    - sqlite3
    - libxml2-dev
    - libxslt1-dev
    - libgdbm-dev
    - libncurses5-dev
    - automake
    - libtool
    - bison
    - libffi-dev
    - bundler
    - lighttpd
    - postfix

  - name: fetch fallingfruit webapp from github
    git: repo=https://github.com/somerandomsequence/falling-fruit.git dest={{ ffhome }}

  - name: update database.yml file
    action: copy src=files/database.yml dest={{ ffhome }}/config/database.yml

  - name: update lighttpd.conf file
    tags: topology
    template: src=files/lighttpd.conf dest=/etc/lighttpd/lighttpd.conf
    
  - name: create crypto directory
    file: path=/etc/lighttpd/crypto owner=www-data group=www-data mode=0700 state=directory

  - name: install ssl key
    action: copy src=files/https.pem dest=/etc/lighttpd/crypto/ff-https.pem

  - name: reload lighttpd config
    tags: topology
    service: name=lighttpd state=reloaded
    
  - name: update thin.yml file
    template: src=files/thin.yml dest={{ ffhome }}/config/thin.yml

  - name: make log directory
    file: path={{ ffhome }}/log owner=www-data group=www-data mode=0755 state=directory

  - name: make tmp directory
    file: path={{ ffhome }}/tmp owner=www-data group=www-data mode=0755 state=directory

  - name: make secrete token
    shell: chdir={{ ffhome }} echo "FallingfruitWebapp::Application.config.secret_token = '`rake secret`'" > config/initializers/secret_token.rb

  - name: change ownership of dir to fallingfruit_user
    command: chown -R www-data:www-data {{ ffhome }}

  - name: change permissions
    command: chmod -R o+rx {{ ffhome }}

  - name: bundle install
    shell: chdir={{ ffhome }} bundle install

  - name: start fallingfruit
    shell: chdir={{ ffhome }} bundle exec thin -e production -C config/thin.yml start
    tags: launch
